package com.maciu19.autobidder.api.auction.model;

import com.maciu19.autobidder.api.shared.enums.EnumString;
import lombok.Getter;

public enum Feature implements EnumString {

    BLUETOOTH("BLUETOOTH", FeatureCategory.AUDIO_TECHNOLOGY),
    USB_PORT("USB_PORT", FeatureCategory.AUDIO_TECHNOLOGY),
    AUXILIARY_INPUT("AUXILIARY_INPUT", FeatureCategory.AUDIO_TECHNOLOGY),
    APPLE_CARPLAY("APPLE_CARPLAY", FeatureCategory.AUDIO_TECHNOLOGY),
    ANDROID_AUTO("ANDROID_AUTO", FeatureCategory.AUDIO_TECHNOLOGY),
    NAVIGATION_SYSTEM("NAVIGATION_SYSTEM", FeatureCategory.AUDIO_TECHNOLOGY),
    TOUCHSCREEN_DISPLAY("TOUCHSCREEN_DISPLAY", FeatureCategory.AUDIO_TECHNOLOGY),
    WIRELESS_PHONE_CHARGING("WIRELESS_PHONE_CHARGING", FeatureCategory.AUDIO_TECHNOLOGY),

    AIR_CONDITIONING("AIR_CONDITIONING", FeatureCategory.COMFORT_EQUIPMENT),
    DUAL_ZONE_CLIMATE_CONTROL("DUAL_ZONE_CLIMATE_CONTROL", FeatureCategory.COMFORT_EQUIPMENT),
    FOUR_ZONE_CLIMATE_CONTROL("FOUR_ZONE_CLIMATE_CONTROL", FeatureCategory.COMFORT_EQUIPMENT),
    HEATED_FRONT_SEATS("HEATED_FRONT_SEATS", FeatureCategory.COMFORT_EQUIPMENT),
    HEATED_REAR_SEATS("HEATED_REAR_SEATS", FeatureCategory.COMFORT_EQUIPMENT),
    VENTILATED_SEATS("VENTILATED_SEATS", FeatureCategory.COMFORT_EQUIPMENT),
    MASSAGE_SEATS("MASSAGE_SEATS", FeatureCategory.COMFORT_EQUIPMENT),
    POWER_ADJUSTABLE_SEATS("POWER_ADJUSTABLE_SEATS", FeatureCategory.COMFORT_EQUIPMENT),
    MEMORY_SEATS("MEMORY_SEATS", FeatureCategory.COMFORT_EQUIPMENT),
    HEATED_STEERING_WHEEL("HEATED_STEERING_WHEEL", FeatureCategory.COMFORT_EQUIPMENT),
    POWER_WINDOWS_FRONT("POWER_WINDOWS_FRONT", FeatureCategory.COMFORT_EQUIPMENT),
    POWER_WINDOWS_REAR("POWER_WINDOWS_REAR", FeatureCategory.COMFORT_EQUIPMENT),
    SUNROOF("SUNROOF", FeatureCategory.COMFORT_EQUIPMENT),
    PANORAMIC_ROOF("PANORAMIC_ROOF", FeatureCategory.COMFORT_EQUIPMENT),
    KEYLESS_ENTRY("KEYLESS_ENTRY", FeatureCategory.COMFORT_EQUIPMENT),
    KEYLESS_GO("KEYLESS_GO", FeatureCategory.COMFORT_EQUIPMENT),
    POWER_TAILGATE("POWER_TAILGATE", FeatureCategory.COMFORT_EQUIPMENT),
    HEATED_MIRRORS("HEATED_MIRRORS", FeatureCategory.COMFORT_EQUIPMENT),
    POWER_FOLDING_MIRRORS("POWER_FOLDING_MIRRORS", FeatureCategory.COMFORT_EQUIPMENT),
    RAIN_SENSOR("RAIN_SENSOR", FeatureCategory.COMFORT_EQUIPMENT),
    LIGHT_SENSOR("LIGHT_SENSOR", FeatureCategory.COMFORT_EQUIPMENT),

    REAR_PARKING_SENSORS("REAR_PARKING_SENSORS", FeatureCategory.ELECTRONICS_ASSISTANCE),
    FRONT_PARKING_SENSORS("FRONT_PARKING_SENSORS", FeatureCategory.ELECTRONICS_ASSISTANCE),
    REAR_VIEW_CAMERA("REAR_VIEW_CAMERA", FeatureCategory.ELECTRONICS_ASSISTANCE),
    SURROUND_VIEW_CAMERAS("SURROUND_VIEW_CAMERAS", FeatureCategory.ELECTRONICS_ASSISTANCE),
    PARKING_ASSIST("PARKING_ASSIST", FeatureCategory.ELECTRONICS_ASSISTANCE),
    CRUISE_CONTROL("CRUISE_CONTROL", FeatureCategory.ELECTRONICS_ASSISTANCE),
    ADAPTIVE_CRUISE_CONTROL("ADAPTIVE_CRUISE_CONTROL", FeatureCategory.ELECTRONICS_ASSISTANCE),
    LANE_KEEP_ASSIST("LANE_KEEP_ASSIST", FeatureCategory.ELECTRONICS_ASSISTANCE),
    BLIND_SPOT_MONITOR("BLIND_SPOT_MONITOR", FeatureCategory.ELECTRONICS_ASSISTANCE),
    TRAFFIC_SIGN_RECOGNITION("TRAFFIC_SIGN_RECOGNITION", FeatureCategory.ELECTRONICS_ASSISTANCE),
    HEAD_UP_DISPLAY("HEAD_UP_DISPLAY", FeatureCategory.ELECTRONICS_ASSISTANCE),
    AUTOMATIC_HEADLIGHTS("AUTOMATIC_HEADLIGHTS", FeatureCategory.ELECTRONICS_ASSISTANCE),
    HIGH_BEAM_ASSIST("HIGH_BEAM_ASSIST", FeatureCategory.ELECTRONICS_ASSISTANCE),
    LED_HEADLIGHTS("LED_HEADLIGHTS", FeatureCategory.ELECTRONICS_ASSISTANCE),
    BI_XENON_HEADLIGHTS("BI_XENON_HEADLIGHTS", FeatureCategory.ELECTRONICS_ASSISTANCE),
    ADAPTIVE_HEADLIGHTS("ADAPTIVE_HEADLIGHTS", FeatureCategory.ELECTRONICS_ASSISTANCE),

    ALL_WHEEL_DRIVE("ALL_WHEEL_DRIVE", FeatureCategory.PERFORMANCE),
    AIR_SUSPENSION("AIR_SUSPENSION", FeatureCategory.PERFORMANCE),
    ADAPTIVE_SUSPENSION("ADAPTIVE_SUSPENSION", FeatureCategory.PERFORMANCE),
    DRIVE_MODE_SELECTOR("DRIVE_MODE_SELECTOR", FeatureCategory.PERFORMANCE),
    SPORT_EXHAUST_SYSTEM("SPORT_EXHAUST_SYSTEM", FeatureCategory.PERFORMANCE),
    PERFORMANCE_BRAKES("PERFORMANCE_BRAKES", FeatureCategory.PERFORMANCE),
    PADDLE_SHIFTERS("PADDLE_SHIFTERS", FeatureCategory.PERFORMANCE),

    ABS("ABS", FeatureCategory.SAFETY),
    ESP("ESP", FeatureCategory.SAFETY),
    TRACTION_CONTROL("TRACTION_CONTROL", FeatureCategory.SAFETY),
    EMERGENCY_BRAKE_ASSIST("EMERGENCY_BRAKE_ASSIST", FeatureCategory.SAFETY),
    AUTOMATIC_EMERGENCY_BRAKING("AUTOMATIC_EMERGENCY_BRAKING", FeatureCategory.SAFETY),
    FRONT_AIRBAGS("FRONT_AIRBAGS", FeatureCategory.SAFETY),
    SIDE_AIRBAGS("SIDE_AIRBAGS", FeatureCategory.SAFETY),
    CURTAIN_AIRBAGS("CURTAIN_AIRBAGS", FeatureCategory.SAFETY),
    TIRE_PRESSURE_MONITORING("TIRE_PRESSURE_MONITORING", FeatureCategory.SAFETY),
    ISOFIX("ISOFIX", FeatureCategory.SAFETY);

    private final String id;

    @Getter
    private final FeatureCategory category;

    Feature(String id, FeatureCategory category) {
        this.id = id;
        this.category = category;
    }

    @Override
    public String getId() {
        return id;
    }
}
