server:
  port: 8080

spring:
  main:
    banner-mode: off

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schema: public

  security:
    oauth2:
      resourceserver:
        jwt:
         issuer-uri: "http://localhost:9090/realms/auto-bidder"