spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
         issuer-uri: "http://localhost:9090/realms/auto-bidder"