server:
  port: 8080

spring:
  main:
    banner-mode: off

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  task:
    scheduling:
      enable: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schema: public

  security:
    oauth2:
      resourceserver:
        jwt:
         issuer-uri: "http://localhost:9090/realms/auto-bidder"

scraper:
  schedule:
    cron: 0 0 3 1 * ?

  base-url: https://www.autoevolution.com

  web-driver:
    timeout-seconds: 20

  manufacturers:
    exclude: AC, ACURA, ALPINE, ARIEL, ARTEGA, AURUS, BRISTOL, BUFORI, CATERHAM, DeLorean, DONKERVOORT, DR MOTOR, EAGLE, FISKER, FSO, GEELY, GORDON MURRAY Automotive, GTA Motor logo, GTA Motor, HINDUSTAN, HOLDEN, INEOS, Karma, KTM, LIGHTYEAR, Lucid Motors, Mahindra, MARUSSIA, MARUTI SUZUKI, MORGAN, NIO, PANOZ, PERODUA, PLYMOUTH, Polestar, PROTON, QOROS, RIMAC, RIVIAN, SALEEN, SANTANA, SAMSUNG, SCION, SPYKER, TVR, VinFast, WIESMANN, Xpeng, ZENDER, Zenvo
    min-model-year: 1960

gcp:
  bucket:
    name: autobidder-auction-videos-and-photos

  credentials:
    location: gcp-credentials.json